### ISSUE TITLE
Attempt to discover/list Elastic app installations done via package managers

### ISSUE THREAD

**Issue by geekpete** [elastic/support-diagnostics#168]
When the diag runs, it could try to dump a list of all installed packages of the Elastic stack to identify if apps have been installed via package managers via some other method.

eg: dump all elasticsearch*, logstash*,etc packages from rpm/yum/dnf or apt/dpkg whichever might exist on the particular system.

This might also extend to [Chocolatey](https://chocolatey.org/) for windows and [Homebrew](https://brew.sh/) for OSX (if we want to take the idea that far)

It could help with identifying a problem where both a tarball unzip of an app as well as a package manager installed version of the same app are coexisting and interacting badly in some way.

**Comment by nemonster** [comment]
The diagnostic only gets run on one node. The amount of work involved in doing something this when factored against the number of cases it could apply to just doesn't deliver an adequate ROI.
