### ISSUE TITLE
Capture /etc/*-release to get exact distro details

### ISSUE THREAD

**Issue by jakommo** [elastic/support-diagnostics#173]
Sometimes it would be useful to know the exact distro and version, to do a repro on that exact version.
Capturing `cat /etc/*release` should provide us that info. 
Any better (even more generic)  ideas ? 
I know we already capture `uname -a` but in Ubuntu the kernel version isn't unique enough (due to the [HWE stack backports](https://wiki.ubuntu.com/Kernel/LTSEnablementStack) ) and they do not list the release version.

**Comment by jjfalling** [comment]
I'd suggest using a java lib to capture this. Some distros such as removed /etc/*release and have their own method of determining the distro.

**Comment by jakommo** [comment]
> such as

yes, which one? 

I'm fine with using other methods, we just need a way to uniquely identify a distro version.

**Comment by jjfalling** [comment]
That's a typo. I can't recall off the top of my head.

**Comment by nemonster** [comment]
Actually, I was looking at this one a while back:
https://github.com/redpois0n/oslib

**Comment by nemonster** [comment]
I have that library now and it looks fairly promising, however it's going to require some time to test it so no guarantees on when and if it will happen.

**Comment by nemonster** [comment]
Take a look at the new 6.4-beta output. Specifically the new sysinfo.txt and sysinfo.json files. They should contain quite a bit more information than was previously captured.
