### ISSUE TITLE
Return shard level stats in indices_stats

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/support-diagnostics#177]
Would be useful for diagnosing hot spotting

```
indices_stats: "_stats?level=shards&pretty&human"
```

**Comment by nemonster** [comment]
Do you want that as a separate output?

**Comment by PhaedrusTheGreek** [comment]
Seems that built in would make sense - I don't see it breaking anything as from what I can tell it adds a new key for each index called `shards`

**Comment by ppf2** [comment]
This file can be huge if there are tons of shards in the cluster (and using pretty).  We may also want to check with dev to see if it's expensive to ask for shard level metrics for all indices.  If so, users will have to be careful esp. when running on an interval.

**Comment by nemonster** [comment]
Yes, I may make it a separate option where you specify it via a --type. So you'd have to explicitly call for it if you wanted that kind of output. Run at your own risk.

**Comment by inqueue** [comment]
+1 I am finding more and more where shard level stats would be helpful to have; see the primary and replica divergence issue. I'd be fine to call it without `?pretty` as it can be prettified with `jq` or any text editor with a pretty JSON plugin. Further the way I understand it, Cat APIs are less efficient anyway as it calls shard level stats internally.

**Comment by jpcarey** [comment]
@ppf2 json size should be the only perf concern. I was just chatting with @bleskes and @jasontedor, and they collect all this data for the call no matter what - it just a matter of what is output in the final json.

**Comment by nemonster** [comment]
Incorporated into the upcoming 6.4

**Comment by jpcarey** [comment]
I think we forgot to add it to all the versions. Currently, I only see `level=shards` for `standard-1`.

**Comment by PhaedrusTheGreek** [comment]
I'm also not seeing this in  `"diagVersion" : "6.4.4"`
