### ISSUE TITLE
[DISCUSS] Rename this repo to `support-diagnostics`

### ISSUE THREAD

**Issue by jordansissel** [elastic/support-diagnostics#191]
Reasoning: This tool supports more than just Elasticsearch.

Proposal: Rename this repo to `support-diagnostics`

**Comment by jakommo** [comment]
In general I'm +1 on this. But, I sent out the link to the download and execute instructions in this repo many many times, so we need to find a way to redirect users that still have the link to this repo.
Does GH redirect automatically if a repo is renamed?

**Comment by nemonster** [comment]
It appears the redirect will happen.
[How do I rename a repository?](https://stackoverflow.com/questions/5751585/how-do-i-rename-a-repository-on-github)
[Repository redirects are here](https://github.com/blog/1508-repository-redirects-are-here)

So I will probably do this some time after the next release or so.

**Comment by suyograo** [comment]
Big +1 on this since we're discussing to add ECE diagnostics to this.

**Comment by jjfalling** [comment]
Rename complete

**Comment by jordansissel** [comment]
❤️ ❤️ ❤️
