### ISSUE TITLE
 Error: Could not find or load main class com.elastic.support.diagnostics.DiagnosticApp

### ISSUE THREAD

**Issue by chrisolido** [elastic/support-diagnostics#203]
Im having this issue :

coltapps@uklvadapp092[DEV][scripts] $ sudo find / -name com.elastic.support.diagnostics.DiagnosticApp
coltapps@uklvadapp092[DEV][scripts] $ ./diagnostics.sh --host 10.198.39.5
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Error: Could not find or load main class com.elastic.support.diagnostics.DiagnosticApp
coltapps@uklvadapp092[DEV][scripts] $ **Error: Could not find or load main class com.elastic.support.diagnostics.DiagnosticApp**
-bash: Error:: command not found
coltapps@uklvadapp092[DEV][scripts] $ pwd
/home/coltapps/support-diagnostics-6.3/scripts
coltapps@uklvadapp092[DEV][scripts] $

**Comment by chrisolido** [comment]
so how to fix it

**Comment by nemonster** [comment]
[Download the correct file](https://github.com/elastic/support-diagnostics#installation).

**Comment by PhaedrusTheGreek** [comment]
@nemonster downloading and running from the source tarball is surprisingly common occurrence.    Is it worth either providing a clearer error or removing source downloads from the repo?

**Comment by nemonster** [comment]
I can look into possibly putting something into the script to check for the presence of the jars. AFA removing the source, that's a Github _feature_.  If I could have turned that off via some switch I would certainly have done that a long, long time ago.

**Comment by toby-sutor** [comment]
I can also reproduce this when the distribution package is being executed via `sh diagnostics.sh` instead of `./diagnostics.sh`:

````
$ sh diagnostics.sh
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Error: Could not find or load main class com.elastic.support.diagnostics.DiagnosticApp
Caused by: java.lang.ClassNotFoundException: com.elastic.support.diagnostics.DiagnosticApp

...

$ ./diagnostics.sh 
Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
2021-03-04 09:48:57,908 main ERROR Unable to locate appender "diag" for logger config "root"
Command line options can be displayed with the --help argument. Entering interactive mode.

Bypass the diagnostic version check. Use when internet outbound HTTP access is blocked by a firewall. (Y/N) [N]: 
````
