### ISSUE TITLE
example use with ssl should be --ssl instead of -ssl

### ISSUE THREAD

**Issue by damianpfister** [elastic/support-diagnostics#213]
The example in the [README](https://github.com/elastic/support-diagnostics#local-example) says:

` ./diagnostics.sh --host 10.0.0.20 --type local -u elastic -p -ssl -o /home/admin/log-output`

It would say either:

` ./diagnostics.sh --host 10.0.0.20 --type local -u elastic -p -s -o /home/admin/log-output`

or:

` ./diagnostics.sh --host 10.0.0.20 --type local -u elastic -p --ssl -o /home/admin/log-output`

**Comment by nemonster** [comment]
Resolved by #237
