### ISSUE TITLE
Add flag to disable checking for diagnostic version updates

### ISSUE THREAD

**Issue by jakauppila** [elastic/support-diagnostics#215]
We run our servers in an air-gapped environment and don't have the ability to reach out to Github to check for updates to the tool. It'd be great if we could disable the checking of updates and shave ~30 seconds off from that timing out.

**Comment by jpcarey** [comment]
Just to understand better - having the request actually made is an issue, or would having a short timeout (maybe running in as a parallel thread) would ok?

**Comment by jakauppila** [comment]
No issue with the request itself, just don't want to wait for the timeout.

**Comment by nemonster** [comment]
The request timeout is currently set to 10 seconds so I'm not sure where the 30 seconds is coming from? Did you actually time this or are you going by the value in the configuration file? There will be an option to bypass it in the next version.

**Comment by nemonster** [comment]
And BTW, running a check like this in a parallel thread defeats the entire purpose of this kind of functionality.

**Comment by jakauppila** [comment]
It's actually a bit longer than 30 seconds:
```
09:38:43 INFO  Checking for diagnostic version updates.
09:39:25 WARN  Issue encountered while checking diagnostic version for updates.
09:39:25 WARN  Failed to get current diagnostic version from Github.
09:39:25 WARN  If Github is not accessible from this environemnt current supported version cannot be confirmed.
```

**Comment by nemonster** [comment]
Depends on the nature of the connect. Thinking about it, the request timeout won't even get hit more than likely because no initial connection is getting made. That's a function of the underlying OS and isn't easily customized. The next version will have a bypass flag for these kind of environments.

**Comment by kostasb** [comment]
+1 for having a bypass flag for the version check, I've seen the version check cause some confusion in an air-gapped environment.

**Comment by kostasb** [comment]
I assume this issue can be closed, right @nemonster ?

```
--bypassDiagVerify
   Bypass the diagnostic version check.
   Default: false
```
