### ISSUE TITLE
invalid args will still prompt for credentials

### ISSUE THREAD

**Issue by jpcarey** [elastic/support-diagnostics#216]
I typed `--sl` and instead of exiting immediately (at the validating inputs), it prompted for a password.
```
./diagnostics.sh -h localhost -u elastic --password --sl
Using /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
12:33:10 INFO  Validating inputs...
Password: ^[[A%
```

**Comment by nemonster** [comment]
That's built into the package I use for dealing with arguments as part of the password concealing. I'll need to look into whether there's a way to force ordering and then an exit. But if not, this isn't exactly a critical issue so it may just have to work that way.

**Comment by nemonster** [comment]
Actually I see there's a problem with an initial value that's allowing this to proceed even when there's an issue. Will be fixed in the next version, which will be out in a few days.
