### ISSUE TITLE
add collection for rollup API configuration

### ISSUE THREAD

**Issue by jpcarey** [elastic/support-diagnostics#224]
Need to add collection for the rollup API. Not all 6.x versions have this, so not sure the best way to avoid having it fail for those versions prior to the feature

**Comment by nemonster** [comment]
In next release.

**Comment by polyfractal** [comment]
I think the main item at this point is grabbing all the running jobs (`GET _xpack/rollup/job/*`), which includes the stats for the job.  Everything else we might need to debug would be either in the `_meta` of index mappings, or in the tasks list, so we'd be able to get it from the existing output.
