### ISSUE TITLE
Check /tmp or $ES_TMPDIR available space

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/support-diagnostics#225]
Since ML jobs could crash or degraded due to the /tmp or $ES_TMPDIR getting full, can we add a quick check on this in the tool?
ML job failure could results in ES pile up with tasks and ingestion all broken down. It was very easily overlooked, yet very easy to check with `df`

Thanks!

**Comment by nemonster** [comment]
This is s a corner case, and as this only gets run on one node it has limited effectiveness as an every time check. And if you run it on the master (which is what everyone seems to tell people do), this isn't really even all that useful. 

This is one of those cases where the appropriate thing is just to tell the user to check tmp on the relevant nodes. The diag can't do that. Or create an issue with ML to have them spit out some kind of logged error if the tmp space is low. Or better yet, write it to one of the stats queries we run.

**Comment by CBlaisure** [comment]
Going through our backlog and given the corner case reply, we are going to close this github issue.  We are looking at something similar in the future here.

As a side note, you can ask the customer to check if you think this is the case.
