### ISSUE TITLE
http 400 response does not get saved to file

### ISSUE THREAD

**Issue by jpcarey** [elastic/support-diagnostics#228]
While chatting with @inqueue today, we noticed that certain API endpoints on elasticsearch return a 400 error when things are actually fine. These responses do not get logged to a file. I was thinking about this - and it seems like we should log whatever data we receive to a file - as sometimes these error messages are critical in determining what happened.
 
```
00:51:38.546 [main] INFO  com.elastic.support.diagnostics.commands.AbstractDiagnosticCmd - Currently running query: _cluster/allocation/explain?pretty
00:51:38.548 [main] ERROR com.elastic.support.util.RestExec - Http Status Code: 400, Reason: Bad Request
00:51:38.548 [main] INFO  com.elastic.support.util.RestExec - No data retrieved.
```

```
> GET /_cluster/allocation/explain?pretty HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
>
< HTTP/1.1 400 Bad Request
< content-type: application/json; charset=UTF-8
< content-length: 484
<
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "unable to find any unassigned shards to explain [ClusterAllocationExplainRequest[useAnyUnassignedShard=true,includeYesDecisions?=false]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "unable to find any unassigned shards to explain [ClusterAllocationExplainRequest[useAnyUnassignedShard=true,includeYesDecisions?=false]"
  },
  "status" : 400
}
```

Putting aside that fact that [elasticsearch should respond with an appropriate error code](https://github.com/elastic/elasticsearch/issues/34800), having any and all data regardless of the response code is critical to understanding more about what failed.

**Comment by nemonster** [comment]
>> These responses do not get logged to a file.

Are you sure about that? I do log any exceptions that occur the diagnostics.log file. Which has been included in every bundle for the last few releases. Here's the thing - I used to put errors in the individual files and got complaints about that. So I moved them to the log.

Does the example you're looking at not have the errors in the logs?

**Comment by jpcarey** [comment]
@nemonster the first example in my prior message was what I received in the log - just the 400 error. The second example shows the 400 response body, which would be nice to capture somewhere for troubleshooting purposes

**Comment by nemonster** [comment]
I circled back to this and it's a combination of a couple of things. One of which was someone logged an issue a while back complaining about those kinds of errors in the actual file output. When I was reworking the logging, I was intending to write this out to the debug log. But looking over it, there are some edge cases where this gets more difficult. So I'm reverting this back to writing all the output I get back to the file even if it's not a 200 response code. It also allows me to simplify the execution logic significantly. It will be out in the next release.
