### ISSUE TITLE
[Feature request] Add ping to all nodes process to support diagnostics

### ISSUE THREAD

**Issue by kunisen** [elastic/support-diagnostics#230]
Once I had cluster down and red issue, I pinged all my 25 nodes (simple curl -XGET to `_cat/health` endpoint) and found 1 node didn't respond timely.
Then I restarted that node and the cluster became green after that.
With that said, I feel it is important to have this.
Appreciate if you can think the needs of this and add this to support diagnostics.

**Comment by nemonster** [comment]
This has been in the diag from the beginning:

```
cat_health: "/_cat/health?v"
```
