### ISSUE TITLE
[Feature Request] Can we add the tool to collect the disk type to check its SSD or not?

### ISSUE THREAD

**Issue by kunisen** [elastic/support-diagnostics#231]
like mentioned in this link.
https://unix.stackexchange.com/questions/65595/how-to-know-if-a-disk-is-an-ssd-or-an-hdd

**Comment by nemonster** [comment]
I don't think this is all that good a candidate for something to be run every time. As the thread indicates, this isn't useful if there's a RAID controller or if it's a virtual environment. Add to that the issue that this is only on one host for the cluster so it's not even fully representative. I think in most cases it's probably more accurate just to ask what kind of storage they have. And if they don't know you can always have them run it and see.

**Comment by nemonster** [comment]
Might be, but I looked into this and in the discussion on adding it to Lucene it's not necessarily all that reliable for the reasons I mentioned above it has issues with virtualized settings and RAID controllers. Unless you can detect that you're running on VMWare, Virtual Box, etc. it's reading you can't trust. On just one host as well.

**Comment by CBlaisure** [comment]
This is not feasible at this time.  Closing but will have it in our repo for future reference.
