### ISSUE TITLE
Add option to collect all logs from all individual nodes from the cluster

### ISSUE THREAD

**Issue by sasubillis** [elastic/support-diagnostics#251]
With this option, it should be possible to collect all logs even old rotated logs form elastic process on all nodes in the cluster will be very beneficial most of the times.

**Comment by nemonster** [comment]
Actually, you get rotated logs (up to 3 rollovers). Given the potential sizes, that's all it's going to get. 

As for getting logs for all nodes in the cluster, I don't think so as long as the overall running convention exists as it does today. You can't get logs via the Elasticsearch API. You have to SSH into the other hosts containing the nodes in the cluster and with that same login have access to the directories where those logs exist. And it's not uncommon to have installations where there may be multiple sets of credentials involved. You wouldn't think so, but if I had not seen it I would not be worried about it. In any case it assumes that you would need an additional level of authentication and a way of accessing those hosts in an OS agnostic fashion. Or at least have the means to seamlessly enable/disable based on capability.

And keep in mind that in the case where you collect logs now you are running on a host with a node. So you're also doing a lot of IO intensive work on a node that may well be in distress already. Not to mention that if you go get the logs from every node in a a cluster and there are 200 nodes in that cluster you are probably going to need a lot of space. 

In its current form, this is just impractical. And there's no way I'm going to build it into this particular application platform.

At some stage in the future however, I might look into putting up a GUI application that runs locally on a workstation, and that has the capability of going out to a selection of nodes and obtaining both logs and system stats. But I'd probably impose some limits on that selection. Either on a "you decide" basis or by doing an initial query and making suggestions on which ones to get logs from.

But that's a way down the road.
