### ISSUE TITLE
incorrect permissions should provide a warning of incomplete data

### ISSUE THREAD

**Issue by jpcarey** [elastic/support-diagnostics#262]
If a user collects a support diagnostic without superuser permissions, the `.security` will not be present in any of the API diagnostic data. This can be easily overlooked for things like having the `.security` in read-only mode. 

We should provide a warning if the user does not contain appropriate permissions to collect the diagnostic.

**Comment by CBlaisure** [comment]
@nemonster Do we have an effort level here? Thanks

**Comment by nemonster** [comment]
Done.
