### ISSUE TITLE
Collect ILM explain API output

### ISSUE THREAD

**Issue by gwbrown** [elastic/support-diagnostics#271]
The output of the [ILM Explain API](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-explain-lifecycle.html) is necessary to troubleshoot most ILM-related issues, so we should collect that data here as well.

Collecting this is as simple as a call to `GET */_ilm/explain?human`. I'm happy to do any work involved here but I'm not familiar with this code at all and I wanted to open an issue so it doesn't get forgotten.

**Comment by inqueue** [comment]
Beats 7.0.0 enables ILM by default in 7.0.0 (when Elasticsearch is licensed for it), so it could be useful to have this one soon.

**Comment by ppf2** [comment]
While we are at it, let's add these too :)

GET /_ilm/status
GET _ilm/policy (so we don't have to dig through the cluster state for it)

**Comment by gwbrown** [comment]
I've opened https://github.com/elastic/support-diagnostics/pull/272 which should add this information.

@ppf2 Good call, I had `_ilm/policy` but I've added `_ilm/status` as well.

**Comment by ppf2** [comment]
Thanks!
