### ISSUE TITLE
[diag][tooling] Break out api's by sub-folder

### ISSUE THREAD

**Issue by aliciascott** [elastic/support-diagnostics#277]
## Idea synopsis
Because there is so much good information in the diagnostic bundle now, would it be possible to list/group the api's by folder?

Example:
***ILM***
--ilm_explain.json
--ilm_policies.json
--ilm_status.json

***CCR***
--ccr_stats.json
--ccr_follower_info.json
--ccr_autofollow_patterns.json

***ML***
--ml_anomaly_detectors.json
--ml_datafeeds.json
--ml_stats.json

***Watcher***
--watcher*.json

***Rollup***
--rollup*.json

#### Use case
It would help to have the features not always used be listed in folders, but the general `cat_*` api's and `cluster` settings etc still in the base folder, for easier reading.

This is just an idea of course!

**Comment by nemonster** [comment]
Added in 7.1.3.
