### ISSUE TITLE
sha1 sum of version 7.0.5 does not match

### ISSUE THREAD

**Issue by jakommo** [elastic/support-diagnostics#278]
The sha1 sum file for `7.0.5` does not match actual 7.0.5 zip file:
```
~/Downloads  cat support-diagnostics-7.0.5-dist.zip.sha1 
a6acb26e1d015f3914af0257f5e1821cc9f9da6e

~/Downloads  sha1sum support-diagnostics-7.0.5-dist.zip 
c1ba2b37e5e282c9209b67038988608dddaea4f5  support-diagnostics-7.0.5-dist.zip
```
@nemonster can you have a look at this? 

Looks like the sha1 file was initially missing https://github.com/elastic/support-diagnostics/issues/274.

**Comment by robin13** [comment]
Reported by customer in case [00340219](https://elastic.my.salesforce.com/5004M00000XpoUQ?srPos=0&srKp=500)

**Comment by nemonster** [comment]
Will take a look, Could have sworn I used what got created for that last build.

**Comment by nemonster** [comment]
Fixed. New release up there now.
