### ISSUE TITLE
Getting error NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by chris-gabler** [elastic/support-diagnostics#284]
I am trying to run diagnostics against Elasticsearch v.7
Here are the contents of log file:
```
09:24:50.210 [main] INFO  com.elastic.support.diagnostics.commands.GenerateManifestCmd - Writing diagnostic manifest.
09:24:50.364 [main] INFO  com.elastic.support.diagnostics.commands.VersionCheckCmd - Getting Elasticsearch Version.
09:24:50.815 [main] INFO  com.elastic.support.diagnostics.commands.DiagVersionCheckCmd - Checking for diagnostic version updates.
09:24:51.163 [main] DIAG  com.elastic.support.diagnostics.chain.DiagnosticChainExec - Error encountered running diagnostic. See logs for additional information.  Exiting application.
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:662) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
	at com.elastic.support.diagnostics.commands.RunClusterQueriesCmd.buildStatementsByVersion(RunClusterQueriesCmd.java:37) ~[support-diagnostics-7.0.6.jar:7.0.6]
	at com.elastic.support.diagnostics.commands.RunClusterQueriesCmd.execute(RunClusterQueriesCmd.java:28) ~[support-diagnostics-7.0.6.jar:7.0.6]
	at com.elastic.support.diagnostics.chain.Chain.execute(Chain.java:33) ~[support-diagnostics-7.0.6.jar:7.0.6]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:18) [support-diagnostics-7.0.6.jar:7.0.6]
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:57) [support-diagnostics-7.0.6.jar:7.0.6]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31) [support-diagnostics-7.0.6.jar:7.0.6]
```
Seems like it cannot parse elastic version or something... Also, it works fine with elastic v.6

**Comment by inqueue** [comment]
Hi @chris-gabler, can you post the full cluster _major.minor.patch_ version? Thanks!

**Comment by chris-gabler** [comment]
Hi @inqueue! It's 7.0.1
{
    "name": "elk-node-1",
    "cluster_name": "esupport-analytics",
    "cluster_uuid": "al9OlOOQQUqrFPmjR4LugQ",
    "version": {
        "number": "7.0.1",
        "build_flavor": "default",
        "build_type": "deb",
        "build_hash": "e4efcb5",
        "build_date": "2019-04-29T12:56:03.145736Z",
        "build_snapshot": false,
        "lucene_version": "8.0.0",
        "minimum_wire_compatibility_version": "6.7.0",
        "minimum_index_compatibility_version": "6.0.0-beta1"
    },
    "tagline": "You Know, for Search"
}

**Comment by nemonster** [comment]
@chris-gabler 

```
java.lang.NumberFormatException: For input string: ""
```

Indicates it didn't get a version at all. What does the command line look like for the execution, and what kind of elasticsearch account are you using to authenticate?

**Comment by chris-gabler** [comment]
@nemonster sudo bash diagnostics.sh --host 169.62.190.149 -u elastic -p <password> -s --noVerify

**Comment by chris-gabler** [comment]
elastic user has admin rights

**Comment by nemonster** [comment]
@chris-gabler I just tested the current diagnostic against a newly minted 7.0.1 cluster and it works fine with the same options.

But I _am_ curious on your command syntax:
```
sudo bash diagnostics.sh 
```
I've never seen anyone prepend the *_bash_* to the command before and generally speaking you are supposed to run from the diagnostic install directory.  So usually I'd expect to see something along the lines of:
```
sudo ./diagnostics.sh --host 169.62.190.149 -u elastic -p password -s --noVerify
```
Can you try that and see what the result is?

**Comment by chris-gabler** [comment]
@nemonster same result. Also I tried executing this command from my local station specifying --type remote. I used the command "./diagnostics.bat --host 169.62.190.149 --type remote -u elasticsearch -p password -s --noVerify". It gave me the same error

**Comment by nemonster** [comment]
OK, can you start from scratch and first just use a zip distribution on your Windows workstation (since you were using .bat" on the remote assuming it's windows). Single node, localhost, no security, no SSL, just bare bones. Can you run against that?

Main issue here is that the same version work for me and they're working for a lot of other people. If that skeletal version errors out, is it possible to send me the contents of the _diagnostics_ temp directory it creates. That will have the log and manifest?

**Comment by chris-gabler** [comment]
Finally I solved it. The reason was that my password had special symbols that I needed to escape... So it assumed the password was wrong and couldn't connect to the server. Thanks for you help!

**Comment by nemonster** [comment]
Curious on the symbols you used? Can you share what those were? I can try to get some auto handling of those things in there.

**Comment by chris-gabler** [comment]
It was like "-p pas$word", which I needed to turn into "-p pas\$word". It would have worked on Windows if I hadn't been using git bash which is a unix shell actually...
