### ISSUE TITLE
[7.0.6] Diagnostics.bat RuntimeException: DiagnosticService runtime error

### ISSUE THREAD

**Issue by maggieghamry** [elastic/support-diagnostics#285]
Support diagnostics against 7.0.6 GA is resulting in java.lang.RuntimeException on Windows 2016.  Security is turned on, but the password has special characters and is being treated as two arguments.  (Incidentally, successfully tested on Windows with fresh install, no security or proxy, with ` .\diagnostics.bat --host localhost --bypassDiagVerify`)
 
#267 seems related (diagnostics.sh version)

The following all result in the error below:

`.\diagnostics.bat --host localhost --bypassDiagVerify`

`.\diagnostics.bat --host localhost --bypassDiagVerify --ssl`

`.\diagnostics.bat --host localhost --bypassDiagVerify --noVerify`

`.\diagnostics.bat --host localhost --bypassDiagVerify --ssl`

`.\diagnostics.bat --host localhost (or IP address) -u <username> -p --ssl --noVerify  --bypassDiagVerify`

```
PS D:\programs\support-diagnostics-7.0.6> .\diagnostics.bat --host localhost --bypassDiagVerify --ssl

JAVA_HOME found, using D:\Java64\Java\JDK\jre

15:42:12 INFO  Processing diagnosticInputs...

15:42:13 INFO  Creating temp directory: D:\programs\support-diagnostics-7.0.6\diagnostics

15:42:13 INFO  Created temp directory: D:\programs\support-diagnostics-7.0.6\diagnostics

15:42:13 INFO  Configuring log file.

15:42:13 INFO  Writing diagnostic manifest.

15:42:13 INFO  Getting Elasticsearch Version.

15:42:13 INFO  Log close complete.

Exception in thread "main" java.lang.RuntimeException: DiagnosticService runtime error

        at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:22)

        at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:57)

        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31)

PS D:\programs\support-diagnostics-7.0.6> .\diagnostics.bat --host localhost --bypassDiagVerify --noVerify

JAVA_HOME found, using D:\Java64\Java\JDK\jre

15:46:31 INFO  Processing diagnosticInputs...

15:46:32 INFO  Creating temp directory: D:\programs\support-diagnostics-7.0.6\diagnostics

15:46:32 INFO  Created temp directory: D:\programs\support-diagnostics-7.0.6\diagnostics

15:46:32 INFO  Configuring log file.

15:46:32 INFO  Writing diagnostic manifest.

15:46:32 INFO  Getting Elasticsearch Version.

15:46:32 INFO  Log close complete.

Exception in thread "main" java.lang.RuntimeException: DiagnosticService runtime error

        at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:22)

        at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:57)

        at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31)

```
 
![2019-06-12 at 2 59 PM](https://user-images.githubusercontent.com/46542915/59384441-2c23c880-8d30-11e9-9a35-aeda006d5884.jpeg)

**Comment by IAmFQQ** [comment]
Also met this issue
qiafan@pronto-g3-hmld12h-slc07-1552293062-1-2783986:~/support-diagnostics-7.0.6$ sudo sh diagnostics.sh --host pronto-g3-hmld12h-slc07-1552293062-1-2783986.stratus.slc.ebay.com  --port 9200
Using /usr/share/pronto-java/jdk/bin/java as Java Runtime
diagnostics.sh: 16: diagnostics.sh: [[: not found
diagnostics.sh: 18: diagnostics.sh: [[: not found
Using   for options.
23:28:32 INFO  Processing diagnosticInputs...
23:28:32 INFO  Creating temp directory: /home/qiafan/support-diagnostics-7.0.6/diagnostics
23:28:32 INFO  Created temp directory: /home/qiafan/support-diagnostics-7.0.6/diagnostics
23:28:32 INFO  Configuring log file.
23:28:32 INFO  Writing diagnostic manifest.
23:28:33 INFO  Getting Elasticsearch Version.
23:28:33 INFO  Checking for diagnostic version updates.
23:29:33 INFO  Issue encountered while checking diagnostic version for updates.
23:29:33 INFO  Failed to get current diagnostic version from Github.
23:29:33 INFO  If Github is not accessible from this environemnt current supported version cannot be confirmed.
23:29:33 INFO  Running query:alias -  /_alias?pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_aliases -  /_cat/aliases?v
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_allocation -  /_cat/allocation?v
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_count -  /_cat/count
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_fielddata -  /_cat/fielddata?v
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_health -  /_cat/health?v
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_indices -  /_cat/indices?v&s=index
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_master -  /_cat/master?format=json
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_nodes -  /_cat/nodes?v&h=n,m,i,r,d,hp,rp,cpu,load_1m,load_5m,load_15m,nodeId
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_pending_tasks -  /_cat/pending_tasks?v
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_segments -  /_cat/segments?v&s=index
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_recovery -  /_cat/recovery?v
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_shards -  /_cat/shards?v&s=index
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_thread_pool -  /_cat/thread_pool?v
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cluster_health -  /_cluster/health?pretty
23:29:33 INFO  Results written to: /home/qiafan/support-diagnostics-7.0.6/diagnostics/cluster_health.json
23:29:33 INFO  Running query:cluster_pending_tasks -  /_cluster/pending_tasks?pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cluster_settings -  /_cluster/settings?pretty&flat_settings
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cluster_state -  /_cluster/state?pretty&human
23:29:33 INFO  Authentication failure: invalid login credentials. Check logs for details.
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cluster_stats -  /_cluster/stats?pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:fielddata -  /_cat/fielddata?format=json&bytes&pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:fielddata_stats -  /_nodes/stats/indices/fielddata?level=shards&pretty=true&fields=*
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:indices_stats -  /_stats?level=shards&pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:mapping -  /_mapping?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:master -  /_cat/master?format=json
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:nodes_hot_threads -  /_nodes/hot_threads?threads=10000
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:nodes_stats -  /_nodes/stats?pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:nodes -  /_nodes?pretty&human
23:29:33 INFO  Authentication failure: invalid login credentials. Check logs for details.
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:plugins -  /_cat/plugins?format=json
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:recovery -  /_recovery?pretty&human&detailed=true
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:segments -  /_segments?pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:settings -  /_settings?pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:shards -  /_cat/shards?format=json&bytes=b&pretty
23:29:33 INFO  Authentication failure: invalid login credentials. Check logs for details.
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:templates -  /_template?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:version -  /
23:29:33 INFO  Results written to: /home/qiafan/support-diagnostics-7.0.6/diagnostics/version.json
23:29:33 INFO  Running query:watcher_stats -  /_watcher/stats/_all
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:watcher_stack -  /_watcher/stats?emit_stacktraces=true
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:licenses -  /_license?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_nodeattrs -  /_cat/nodeattrs?v&h=node,id,pid,host,ip,port,attr,value
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cat_repositories -  /_cat/repositories?v
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:count -  /_count
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:security_users -  /_xpack/security/user?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:security_roles -  /_xpack/security/role?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:shard_stores -  /_shard_stores?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:tasks -  /_tasks?pretty&human&detailed=true
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:allocation_explain -  /_cluster/allocation/explain?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:allocation_explain_disk -  /_cluster/allocation/explain?include_disk_info=true&pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:ml_anomaly_detectors -  /_xpack/ml/anomaly_detectors?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:ml_datafeeds -  /_xpack/ml/datafeeds?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:ml_stats -  /_xpack/ml/anomaly_detectors/_stats?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:pipelines -  /_ingest/pipeline/*?pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:security_role_mappings -  /_xpack/security/role_mapping?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:xpack -  /_xpack/usage?pretty&human
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:nodes_usage -  /_nodes/usage?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:remote_cluster_info -  /_remote/info
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:rollup_jobs -  /_xpack/rollup/job/_all
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:rollup_caps -  /_xpack/rollup/data/_all
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:cluster_settings_defaults -  /_cluster/settings?include_defaults&pretty&flat_settings
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:rollup_index_caps -  /*/_xpack/rollup/data
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:security_priv -  /_xpack/security/privilege?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:ccr_stats -  /_ccr/stats?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Running query:ccr_autofollow_patterns -  /_ccr/auto_follow?pretty
23:29:33 INFO  Call failed. Bypassing.
23:29:33 INFO  Checking the supplied hostname against the node information retrieved to verify location. This may take some time if localhost was specified in a multi-node cluster
23:29:33 INFO  Log close complete.
Exception in thread "main" java.lang.RuntimeException: DiagnosticService runtime error
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:22)
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:57)
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31)

**Comment by IAmFQQ** [comment]
fixed by -u and --ptp

**Comment by maggieghamry** [comment]
Thanks @IAmFQQ - the --ptp is noted as "inherently insecure", so it's unfortunately not an option.

**Comment by maggieghamry** [comment]
It turns out this had a very simple fix - the username was incorrectly entered as `-u Elastic` instead of `-u elastic` - diags ran successfully after that !
