### ISSUE TITLE
logstash diagnostic tool hot threads and multiple snapshot options

### ISSUE THREAD

**Issue by sophiaxu8** [elastic/support-diagnostics#287]
When analyzing stalling/slow data processing, a single logstash diagnostic snapshot of the metric apis can be limiting. Could the logstash diagnostic tool have option  to take 2 or 3 snapshots in a 5 second interval so we can understand if data is stalling?  And also Logstash diagnostic tool by default collect the top 3 hot threads, we often had to ask the customer to fetch hot_threads separately.

**Comment by jsvd** [comment]
Big +1 on requesting the [node stats and the hot threads](https://github.com/elastic/support-diagnostics/blob/master/src/main/resources/logstash-rest.yml#L25-L31) apis 3 times, separated by 5 seconds.

> And also Logstash diagnostic tool by default collect the top 3 hot threads, we often had to ask the customer to fetch hot_threads separately.

Looking at https://github.com/elastic/support-diagnostics/pull/327/files#diff-9d6cdc871cc6fcc4bc98f4757b88f9a1R33 it seems we'll request the top 10_000.

**Comment by nemonster** [comment]
In the next release you can specify x number of runs separated by a defined interval.
