### ISSUE TITLE
Cluster behind LB (F5, specifically)

### ISSUE THREAD

**Issue by edsyoo** [elastic/support-diagnostics#296]
When using VIP of F5 Loadbalancer, diagnostic failed.  

When directing the diagnostic directly to a node in the cluster, it was fine.  

I was curious if accessing a cluster behind an LB was a known issue for the diagnostic or is this an odd case?

Output:
```
sudo ./diagnostics.sh --host hostname.com --port 11111

Using /usr/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
18:57:36 INFO  Processing diagnosticInputs...
18:57:37 INFO  Creating temp directory: /mnt/c/Temp/elasticsearch/support-diagnostics-7.0.8/diagnostics
18:57:37 INFO  Created temp directory: /mnt/c/Temp/elasticsearch/support-diagnostics-7.0.8/diagnostics
18:57:37 INFO  Configuring log file.
18:57:37 INFO  Writing diagnostic manifest.
18:57:38 INFO  Checking for diagnostic version updates.
18:57:38 INFO  Getting Elasticsearch Version.
18:57:38 INFO  Log close complete.
Exception in thread "main" java.lang.RuntimeException: DiagnosticService runtime error
       at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:22)
       at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:59)
       at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31)
```

**Comment by nemonster** [comment]
There isn't sufficient information here to determine what actually went wrong. It appears that it failed on the version check. Which would indicate a connectivity issue. But looking over the URL, it's not apparent to me how that relates to the F5 setup and the cluster? Does the URL submitted to the F5 contain the port? There's no description of the actual setup here. 

But from the command line, I would definitely question why you would even do this to begin with? If you check the README for the diagnostic, you'll see that in the default case this was intended to be run from a host that contains a diagnostic. And that it is going to execute certain calls on that host and try to retrieve the logs. So given the nature of load balancers and why you use them, I'm a little confused on why you want to run what is essentially a targeted administrative function in a distributed fashion? 

It would make more sense to run it with --type remote in a case like this. Although I don't think that's what is going wrong. If you ping me directly in Slack with the log that gets created in the resulting archive I'd have a better idea. But even then this is usage contrary to the instructions so while I can possibly explain _why_ it happened I doubt this is a use case we want to support.
