### ISSUE TITLE
Java options for Elasticsearch version 7.X and newer

### ISSUE THREAD

**Issue by jaalcorn** [elastic/support-diagnostics#306]
[0,2,2,2]
Currently if $JAVA_HOME isn't defined on the host and the script cannot find the java executable in the path check, it will not run. 

Since elasticsearch now comes bundled with openjdk it would be good to either use that executable or allow passing the java path to the script manually, since there will probably be more cases of hosts without java manually installed and $JAVA_HOME set in the future.

Thank you.

**Comment by nemonster** [comment]
[0,2,2,2]
2

**Comment by nemonster** [comment]
I think I may have a more automagic fix for this. Will update shortly.

**Comment by nemonster** [comment]
@jaalcorn Will be addressed in v. 7.0.10.
