### ISSUE TITLE
File sanitazation tool fails with an error

### ISSUE THREAD

**Issue by ntim** [elastic/support-diagnostics#309]
Hi,

when I collect remote support diagnostics with

`/diagnostics.sh --host elasticsearch --ssl -u elastic -p --type remote --port 443`

and then try to scrub the results

`./scrub.sh -o /.../support-diagnostics-7.0.9-dist/support-diagnostics-7.0.9/output/ -a /.../support-diagnostics-7.0.9-dist/support-diagnostics-7.0.9/remote-diagnostics-20190917-102940.tar.gz  -c /.../support-diagnostics-7.0.9-dist/support-diagnostics-7.0.9/scrub.yml`

I get the following error

`
07:23:49.611 [main] ERROR com.elastic.support.scrub.ScrubProcessor - Error initializing scrubbing  files.
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
	at com.elastic.support.scrub.ScrubProcessor.<init>(ScrubProcessor.java:38) [support-diagnostics-7.0.9.jar:7.0.9]
	at com.elastic.support.scrub.ScrubService.exec(ScrubService.java:51) [support-diagnostics-7.0.9.jar:7.0.9]
	at com.elastic.support.scrub.ScrubApp.main(ScrubApp.java:24) [support-diagnostics-7.0.9.jar:7.0.9]
07:23:49.652 [main] DIAG  com.elastic.support.BaseService - Error occurred: 
java.lang.RuntimeException: Scrub initialization failed
	at com.elastic.support.scrub.ScrubProcessor.<init>(ScrubProcessor.java:56) ~[support-diagnostics-7.0.9.jar:7.0.9]
	at com.elastic.support.scrub.ScrubService.exec(ScrubService.java:51) [support-diagnostics-7.0.9.jar:7.0.9]
	at com.elastic.support.scrub.ScrubApp.main(ScrubApp.java:24) [support-diagnostics-7.0.9.jar:7.0.9]
07:23:49.652 [main] ERROR com.elastic.support.BaseService - Issue encountered during scrub processing. Check diagnostics.log in the archive file for more detail..
`

The contents of the _scrub.yml_ have not yet been modified.

I have elastic 7.3.1 and am running on debian buster with openjdk 1.8.0_212.

**Comment by eddieturizo** [comment]
The path to the archive must be an [absolute path](https://github.com/elastic/support-diagnostics#how-to-run).

**Comment by ntim** [comment]
It is, /.../ is only for obfuscation

**Comment by eddieturizo** [comment]
That's fine, but I think it is less confusing to use `/home/foo` over `/...`

Are you able to share `diagnostics.log`? If not, have you looked at the file to see if you're able to get more context?

**Comment by robin13** [comment]
I have seen another case of this.  I'm afraid I cannot share the diagnostics.log...

**Comment by nemonster** [comment]
This portion of the logged message:

```
07:23:49.611 [main] ERROR com.elastic.support.scrub.ScrubProcessor - Error initializing scrubbing files. java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap') at com.elastic.support.scrub.ScrubProcessor.<init>(ScrubProcessor.java:38) [support-diagnostics-7.0.9.jar:7.0.9] at
```

is where the input configuration is initialized. If there are any tokens present, it will try to build a list, and that's where the error occurs. Are you absolutely sure you have not modified the scrub.yml? If you are running with defaults, try again with no input configuration specified at all so it uses the default. If it runs, it's an issue with your configuration.

**Comment by nemonster** [comment]
No response or additional info, so closing.
