### ISSUE TITLE
Automatically update the diagnostics collected

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/support-diagnostics#311]
We recommend running the latest diagnostics tool so we always get the best possible diagnostics, but this imposes a burden on users to upgrade their diagnostics tool each time they run it. For instance, I recently worked an ILM support case but the diagnostics were missing the ILM outputs since they came from an older version of the tool. We discussed this in today's Elasticsearch FixItFriday meeting and agreed to open an issue here to suggest support for some kind of automatic updates for the tool. Our suggestions included:

- completely upgrade itself when a new version is available, similar to `brew`.

- leave the tool as-is but update its definitions of the commands it should run, replacing those in https://github.com/elastic/support-diagnostics/tree/master/src/main/resources 

- simply emit a message that the tool isn't the latest version

Of course none of this will work if the tool doesn't have internet access, but I think that the tool will have internet access in many cases.

**Comment by nemonster** [comment]
@DaveCTurner It already does this. Of course you have to be running a version subsequent to when this was added.

> simply emit a message that the tool isn't the latest version

**Comment by Flygar** [comment]
when make support-diagnostics into a k8s “job”, how to pull the latest version when making a mirror instead of specifying the version number.  
So I want to have  a latest version instead of “the latest version of the specified newest version number”.

**Comment by nemonster** [comment]
@Flygar I don't have anything to do with that - it's Github functionality, so if you want something like that you'll have to submit that request to them. And in any case, that's not precisely what's being discussed in this issue, so the appropriate action in any case would be to create a separate issue rather than piggybacking on this one.

**Comment by nemonster** [comment]
Closing given there's been no response and the functionality requested already exists.

**Comment by DaveCTurner** [comment]
Thanks for the info @nemonster and sorry for the delayed response. I had indeed missed that this feature existed.
