### ISSUE TITLE
Running File Sanitization without an explicit output will overwrite entire current working directory

### ISSUE THREAD

**Issue by b-deam** [elastic/support-diagnostics#316]
When running the File Sanitization `./scrub.sh` included in the Support Diagnostics - if you do not specify an explicit output i.e.

- `Bradleys-MBP:support-diagnostics-7.0.9 bradleydeam$ ./scrub.sh -a ~/remote-diagnostics-20191009-081937.tar.gz`

It will actually overwrite every file inside the current working directory.

- `Bradleys-MBP:support-diagnostics-7.0.9 bradleydeam$ ./scrub.sh -a ~/remote-diagnostics-20191009-081937.tar.gz -o ~/sanitized-diagnostic`

Specifiying an explicit output does what you'd expect, and leaves the current working directory  alone, creating a new output tarball.

Is this expected behaviour? I'd have thought by omitting an explicit output path it'd just create the sanitized-diagnostic inside the current working directory without deleting everything else (including the `./scrub.sh` script itself).

The description of the output switch also doesn't mention anything around overwriting the current working directory if omitted.
 
> -o, --out, --output, --outputDir     A target directory where you want the revised archive written. If not supplied it will be written to the same folder as the diagnostic archive it processed.

**Comment by nemonster** [comment]
Fixed in the next release.

**Comment by nemonster** [comment]
Fixed in 7.1.0

**Comment by nemonster** [comment]
Regression - broken in 7.1.2. Resolved in next release.
