### ISSUE TITLE
Record the node to which diagnostics is connecting in the diagnostics.log

### ISSUE THREAD

**Issue by robin13** [elastic/support-diagnostics#318]
There are times when we request the diagnostics to be taken against the elected master node, but the resulting diagnostics looks as if it was taken against another node:
```
Service Unavailable - {"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}
```

To be able to verify if the diagnostics was actually executed against the correct node in the cluster, it would be helpful if the diagnostics parameters related to the connection including host, port and username (but without password of course) could be shown in the diagnostics log.

**Comment by nemonster** [comment]
That information is already in the manifest.json.Along with the port and any input parameters.

**Comment by robin13** [comment]
Thank you - I did not know that. :)
