### ISSUE TITLE
Failure when running 7.1.5 diagnostic against logstash: Error obtaining logstash output and/or process id

### ISSUE THREAD

**Issue by adoerrES** [elastic/support-diagnostics#348]
When running the 7.1.5 diagnostic against Logstash, the following error is thrown (from the diagnostic.log):

command: `./diagnostics.sh --host xpackNode0 --type logstash --port 9600`

output:  
```
15:44:05.144 [main] INFO  com.elastic.support.diagnostics.commands.GenerateManifest - Writing diagnostic manifest.
15:44:05.160 [main] INFO  com.elastic.support.diagnostics.commands.CheckDiagnosticVersion - Checking for diagnostic version updates.
15:44:05.639 [main] DIAG  com.elastic.support.diagnostics.commands.BaseQuery - Logstash Query error:
java.lang.NullPointerException: null
	at com.elastic.support.diagnostics.commands.RunLogstashQueries.execute(RunLogstashQueries.java:28) [support-diagnostics-7.1.5.jar:7.1.5]
	at com.elastic.support.diagnostics.chain.DiagnosticChainExec.runDiagnostic(DiagnosticChainExec.java:35) [support-diagnostics-7.1.5.jar:7.1.5]
	at com.elastic.support.diagnostics.DiagnosticService.exec(DiagnosticService.java:56) [support-diagnostics-7.1.5.jar:7.1.5]
	at com.elastic.support.diagnostics.DiagnosticApp.main(DiagnosticApp.java:31) [support-diagnostics-7.1.5.jar:7.1.5]
15:44:05.644 [main] WARN  com.elastic.support.diagnostics.DiagnosticService - Error obtaining logstash output and/or process id - exiting. Check diagnostics.log in the archive file for more detail.
```

Diagnostic attached here
[logstash-diagnostics-20191210-154405.tar.gz](https://github.com/elastic/support-diagnostics/files/3947100/logstash-diagnostics-20191210-154405.tar.gz)
 (no sensitive info contained)

**Comment by adoerrES** [comment]
The workaround for this when needing Logstash diagnostics is to just use an older diag version. I can confirm version 7.1.1 works fine for this, and avoids some other issues leading up to 7.1.5.

**Comment by rwaight** [comment]
Thanks for noting the workaround, @adoerrES.  For clarification, it is also mentioned in https://github.com/elastic/support-diagnostics/issues/372#issuecomment-586342354.

**Comment by ankit85jain** [comment]
I am using 9.2.2 version and getting the same error. We are using logstash for batch processing. Means process exits once file is processed.
