### ISSUE TITLE
Document the minimum permissions necessary to run diagnostics

### ISSUE THREAD

**Issue by robin13** [elastic/support-diagnostics#352]
For a secure oriented user who would like to have a dedicated diagnostics user, what are the minimum permissions necessary in elasticsearch to complete a diagnostics?
Could this be added to the documentation?

**Comment by jstrassb** [comment]
@nemonster would you know this?

**Comment by nemonster** [comment]
If you're not concerned with incomplete output on things like the sysctl command then you should be able to get by if you're in the elasticsearch group. You need at minimum that to get the logs.

**Comment by robin13** [comment]
@nemonster Good to know!
Sorry if I wasn't clear - I meant to ask for the minimum elasticsearch privileges...
I would guess the cluster permission `monitor` should do it, but I haven't reviewed all API calls to check if there's anything outside of that.

**Comment by robin13** [comment]
If running with only `monitor` a lot fails and the output indicates that the `superuser` role is necessary:

```
************************************************************
The elasticsearch user entered: test does not appear to have sufficient authorization to access all collected information
Some of the calls may not have completed successfully.
If you are using a custom role please verify that it has the admin role for versions prior to 5.x or the superuser role for subsequent versions.
************************************************************
```

I then tried to make a role with as few permissions as possible (by adding privileges until I had no failures) and came up with this:

```
    "cluster" : [
      "monitor",
      "manage",
      "manage_security"
    ]

and

    "indices" : [
      {
        "names" : [
          "*"
        ],
        "privileges" : [
          "monitor",
          "read",
          "manage"
        ],
        "field_security" : {
          "grant" : [
            "*"
          ],
          "except" : [ ]
        },
        "allow_restricted_indices" : false
      }
    ]
```

But how much less than the `superuser` role is this - is it any advantage to the security conscious user?  I guess one important aspect is that the user cannot index data (but they can delete full indices...)

**Comment by robin13** [comment]
Would it be worth opening an additional issue to have the diagnostics tool query first what permissions the user it is running as has, and to report what permissions are missing (if any are missing) to be able to run completely?  This would be a nice self-documenting solution and could also allow the diagnostics tool to complete quicker because it could elegantly skip over making any API calls which it would not be able to complete anyway.

**Comment by nemonster** [comment]
After internal discussions within the tools group, we will not be acting upon this request.

The diagnostic does not try, nor has ever attempted to maintain a manifest the lowest level of access required for each of the many REST calls. None of these are, nor have ever been specified in the Elasticsearch documentation. And are more than likely controlled by the individual groups who maintain those various API's. To further complicate things, they may have changed over the various versions. Hard to say, it's not documented.

We document what will consistently work across calls/versions:  _Run it with this and it will work_. You can run it with a different set of roles, but we don't guarantee it will succeed for every call. You may get incomplete output. The warning we issue is pretty explicit in that regard. And keep in mind, there is nothing that prevents you from running with a lower level of access. We don't stop you - it's just a warning. We just don't guarantee the result will be complete. That is entirely within the control of who runs the diagnostic.

Given that, I'm not sure why you are requesting this from the diagnostic. It's not really a concern of the utility. Anyone who does not want to run with the superuser role is perfectly free to experiment with any level of access for the particular version they are running and attempt to create a custom role, with exactly the minimum required to get the amount of information they or support consider sufficient. Again, nothing stops you from doing this. But it's outside the scope of the diagnostic to assist with that particular task.

Which comes to this: The proper place to submit the request for granularly documenting the minimum level of the REST calls is with the group that maintains the REST calls, not here. Elastic, Security, Monitoring, Machine Learning, etc. If they consider that worthwhile, we're happy to incorporate the result and provide the necessary links and guidance in the readme. But that is beyond the scope and function of what we provide via this application.

**Comment by robin13** [comment]
> Run it with this and it will work. You can run it with a different set of roles, but we don't guarantee it will succeed for every call.

Fair enough. :)
