### ISSUE TITLE
Error trying to import monitoring data from a diag export

### ISSUE THREAD

**Issue by BobBlank12** [elastic/support-diagnostics#353]
[2,2,2,1]
Monitoring data was exported by a diag and came in a tar.gz format.  I tried importing it with that format, as an uncompressed tar file as well as converted to a zip file.

Command:
`sudo ./import-monitoring.sh --host localhost -u elastic -p -i /Users/my_user/Downloads/monitoring-export-20200104-121315.zip`

Result:
```
Exception in thread "main" java.lang.NullPointerException
	at com.elastic.support.monitoring.MonitoringImportInputs.validate(MonitoringImportInputs.java:53)
	at com.elastic.support.monitoring.MonitoringImportApp.main(MonitoringImportApp.java:16)
```

**Comment by nemonster** [comment]
For now, convert it back to a tar.gz. I would think a zip ought to work, but I'll have to take a closer look. I'm in progress on some changes, but this will get resolved one way or the other in the next release.

**Comment by nemonster** [comment]
After checking, this was not due to tar.gz functionality but rather the missing custom index name issue, which will be fixed in the next release

**Comment by BobBlank12** [comment]
👍

**Comment by nemonster** [comment]
Done and slated for next release.
