### ISSUE TITLE
Test failure on Centos7: top -l

### ISSUE THREAD

**Issue by anyasabo** [elastic/support-diagnostics#377]
I was trying to build on Centos7 and received an error when it was running tests, I believe because top's `-l` option is OSX only. It looks like it is used here:

https://github.com/elastic/support-diagnostics/blob/master/src/test/java/com/elastic/support/diagnostics/commands/TestRemoteSystemCommands.java#L287

```
[INFO] Running com.elastic.support.diagnostics.commands.TestUserRoleCheck
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.886 s - in com.elastic.support.diagnostics.commands.TestUserRoleCheck
[INFO] Running com.elastic.support.diagnostics.commands.TestRemoteSystemCommands
23:54:40 INFO  com.jcraft.jsch.JSchException: timeout: socket is not established
23:54:40 INFO  top: unknown option 'l'
Usage:
  top -hv | -bcHiOSs -d secs -n max -u|U user -p pid(s) -o field -w [cols]
```

**Comment by CBlaisure** [comment]
@nemonster discussed.  Closing issue.  Thank you.
