### ISSUE TITLE
Configurable delay between API calls

### ISSUE THREAD

**Issue by jstrassb** [elastic/support-diagnostics#385]
[1,1,2,1]
For busy clusters it can be overwhelming to respond to all the request from the diagnostic script in a short time. With a configurable delay of `x` seconds between attempts it would allow some breathing room to Elasticsearch.

This should hopefully allow to grab a full diagnostic instead of just a partial one.
Bonus points for a 'minimum mode' that gets one at least the needed data to do the graphical analysis.

I could not find anything along these lines yet so opened this issue.
Having to ask customers individual API calls is possible but can be quite extensive, having them just try to increment the time and let the diag script take an hour if needed could help here.

**Comment by nemonster** [comment]
Do you have a diagnostic that shows these timeouts occurring? Not necessarily opposed to looking into this. but I'd like to see some evidence that putting this kind of pause in there actually does anything. Generally speaking the only things that time out are nodes, nodes_stats, shards, and cluster_state which are all heavy by nature in a big cluster. 

As far as a minimum files run just for the analyzer, I'm actually already looking into that, with the idea of producing multiple timed runs over the course of a given time period.

**Comment by jstrassb** [comment]
Ah cool, then those functions would be the interesting ones to see if a delay can help.
Will try to find a partial diagnostic where something like that happened.

Thanks for the pointers to the problematic things, though the clusters are not necessarily big where this happens, seen it time out easily as well when the cluster was pegged with tasks, queues full or similar.

Awesome  to hear about the minimum work already being done, thanks as always to help us do our job better :)

**Comment by nemonster** [comment]
In the next release automatic retries will be disabled by default. You'll need to explicitly turn them on from now on. And actually, you can already change the delay between retries with the pause-retries field in diags.yml.
