### ISSUE TITLE
interactive mode the question for a directory doesn't end with a colon

### ISSUE THREAD

**Issue by 111andre111** [elastic/support-diagnostics#393]
Like we see here
https://github.com/elastic/support-diagnostics/blob/master/src/main/java/com/elastic/support/BaseInputs.java#L23
this can be used as a parameter, but it is not obvious, that in interactive mode this can be set as a parameter well.
Maybe changing the string to one, that end with a colon like `:` would help to understand that already.

**Comment by nemonster** [comment]
I'd be curious how else you are going to view this, given that every other prompt in interactive mode wants an input value. And as you say, it's a documented input as well. And most people just take the default and put it in the diag directory anyway. So I can certainly do a colon when I'm making another change but this one will be a lower priority.

**Comment by 111andre111** [comment]
I mean this is more from a cosmetical point of view. It's not consistent that all parameters that are requested have a colon, but this one doesn't, see screenshot, maybe that makes it more clear.

<img width="988" alt="Screenshot 2020-04-08 at 19 54 46" src="https://user-images.githubusercontent.com/48132449/78817598-ac0fd300-79d3-11ea-84df-adb12bc2af24.png">
