### ISSUE TITLE
command completion for zsh and bash

### ISSUE THREAD

**Issue by 111andre111** [elastic/support-diagnostics#394]
I have a feature request for support diagnostics.
It would be very help ful to have a possibility to do a command completion for this tool for bash and zsh at least. Thank you.

**Comment by nemonster** [comment]
Given the limited set of inputs and responses this does not make sense from a cost/benefit perspective. Sorry, but this particular request isn't gong to happen as long as the exists in its current form.

**Comment by 111andre111** [comment]
@nemonster Ok, that's alright. Thank you anyways.
