### ISSUE TITLE
user parameter always needs password parameter

### ISSUE THREAD

**Issue by 111andre111** [elastic/support-diagnostics#396]
[1,0,1,0]

At the moment if I use the `--user ...` parameter and I don't declare the password parameter, then the diagnostics generate an error at the moment:
`unable to continue. Status: 401  Reason: Authentication failure. Invalid login credentials.`

Maybe it would be useful if the tool would not generate an error but fall back to asking interactively for the password.

In this context, I am not sure if this is possible, but if a user had an empty password this would not work either I assume?

Thank you

**Comment by nemonster** [comment]
The library I use to process command line arguments used the -p parameter as a switch so it would open a terminal for input. I essentially do the same thing. It's possible at this stage to do away with it and just prompt for a password for each of those fields. But that does require some rework and makes that case diverge from the other password type fields where you actually _can_ have a user id but no password.

So changing the functionality for this field has at least two drawbacks to my thinking. First, it makes it diverge from the way the others have work. And second, it represents another change from the way it always **has** worked. Which generally takes a while to sink it and creates confusion. 

And it's really not an issue if you use interactive mode. 

Is this a case where you see this often? I tend to see the case where peope try to send in a password with the parameter more often than I do them omitting it entirely.

**Comment by 111andre111** [comment]
I have seen it live in a screensharing session assuming the other side, that this password parameter is not needed if you do declare the user already. I mean especially system administrators that are used to tools like curl or httpie, where you always normally just declare the user parameter and automatically queries for the password even without a parameter. This is the point of view where this is coming from.

**Comment by nemonster** [comment]
Addressed in the next release. Given that it's unusual to run ES now without authentication I am making it the default. You have to disable authentication explicitly if you don't want to apply security. And given that, there will always be a prompt for the user and password fields where both are obfuscated.
