### ISSUE TITLE
diagnostics log mentions an error where there isn't one

### ISSUE THREAD

**Issue by 111andre111** [elastic/support-diagnostics#400]
For the moment support diagnostics mentions this error:
```
<timestamp> [main] INFO  com.elastic.support.diagnostics.commands.BaseQuery - allocation_explain   /_cluster/allocation/explain?pretty  failed. Bypassing
<timestamp> [main] INFO  com.elastic.support.diagnostics.commands.BaseQuery - See archived diagnostics.log for more detail. Status: 400  Reason: Bad Request. Rejected
<timestamp> [main] INFO  com.elastic.support.diagnostics.commands.BaseQuery - allocation_explain_disk   /_cluster/allocation/explain?include_disk_info=true&pretty  failed. Bypassing
<timestamp> [main] INFO  com.elastic.support.diagnostics.commands.BaseQuery - See archived diagnostics.log for more detail. Status: 400  Reason: Bad Request. Rejected
```
But the cluster allocation explain API returns this status code 400 when it is healthy and nothing to do.
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "unable to find any unassigned shards to explain [ClusterAllocationExplainRequest[useAnyUnassignedShard=true,includeYesDecisions?=false]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "unable to find any unassigned shards to explain [ClusterAllocationExplainRequest[useAnyUnassignedShard=true,includeYesDecisions?=false]"
  },
  "status" : 400
}
```
https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html
This issue describes that and that there won't be a solution in short term I assume:
https://github.com/elastic/elasticsearch/issues/34800

So I think it is a difference having this http status 400 versus another message which can be realy errors and the support diagnostics should care about that in my opinion.

**Comment by nemonster** [comment]
If you really care about the full message, it's in the output file. As I have explained a few times, I just stream the output to disk, display the message returned by ES and proceed to the next call. No matter what happens I get as many calls as possible. It has no real impact on the diag running. It _does_ have some impact if the person using it is not familiar with the expected output. So I'll add an entry to the troubleshooting section. That's as far as I think is warranted with this one.

**Comment by pickypg** [comment]
The issue with ignoring 400 here is that you could legitimately cause a 400 ("Bad Request") and not know it at that point.

**Comment by 111andre111** [comment]
No worries. I completely understand that what was said and I brought it up only because of the reason it came up during a diagnostics session and having seen this log line that there were errors. So for the moment I don't have a real good solution for that and I agree with you.
But from a customer's perspective this log line can be a bit irritating asking yourself - hey, why my cluster isn't healthy - but it is health, if you know what I mean.

**Comment by jpcarey** [comment]
Unfortunately, as you probably read from the linked elastic/elasticsearch#34800 issue, the elasticsearch devs decided that the 400 response was appropriate. I think conditionally trying to deal with this one API endpoint to suppress what our elasticsearch team considered valid is a very bad idea. The fix to this should be upstream (the decision has already been made), or a separate enhancement request where we query for unassigned shards and issue allocation explain to only those shards (this is what I did with the [ECE diagnostic](https://github.com/elastic/ece-support-diagnostics/blob/v0/collectors/elasticsearch/runElasticsearch.go#L57-L112))

I think we can close this, given the consensus that ignoring / suppressing is not the right approach.
