### ISSUE TITLE
Running support tools (diag + fsu) against large cluster states and diag bundles 

### ISSUE THREAD

**Issue by eddieturizo** [elastic/support-diagnostics#408]
Goal here is to discuss what metrics we should collect and present as part of discussing possible optimizations that may be needed for either utility (diag, file sanitization) when ran against large clusters (100+ nodes) and diagnostic bundles with large (350+ MB) files. 

It has been observed that the file sanitization utility can take a long time (5+ minutes) to sanitize a JSON file at 354MB. It should be noted that `scrub.yml` used regex rather than token strings.

**Comment by nemonster** [comment]
What heap size were they using when they ran it? If it's the default, I'd try bumping up to 8G or greater.

**Comment by eddieturizo** [comment]
They were in fact running with the default heap settings. The issue is that the cluster state is so large, the scrub utility may benefit from optimizations.

**Comment by nemonster** [comment]
Addressed in the next release.
