### ISSUE TITLE
Collect other monitoring data (Logstash, etc)

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/support-diagnostics#422]
I think by default, the Elasticsearch monitoring data is collected, but it would be great if we had the option to also collect others such as Logstash.  This is good for correlation of pipeline issues.

**Comment by nemonster** [comment]
Don't disagree. Had considered it before, but this is the first time anyone has asked for it. Also think the data from metricbeat might be interesting to have.

**Comment by nemonster** [comment]
@PhaedrusTheGreek Followup on this - you're referring to Metricbeat based monitoring data? Or the legacy collection?

**Comment by nemonster** [comment]
@PhaedrusTheGreek this will be out in this week's release.
