### ISSUE TITLE
Add datafeed stats information to support diagnostic

### ISSUE THREAD

**Issue by benwtrent** [elastic/support-diagnostics#426]
Since 7.4.0 we have had helpful search metrics added to the datafeed stats API https://github.com/elastic/elasticsearch/pull/44683

We should add these statistics along side the anomaly detector statistics.

https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-get-datafeed-stats.html

**Comment by nemonster** [comment]
Will be in the next minor release.

**Comment by ppf2** [comment]
@nemonster It looks like datafeed stats existed since 5.5 (https://www.elastic.co/guide/en/elasticsearch/reference/5.5/ml-get-datafeed-stats.html) so I think we will want to update this construct to:

```
ml_datafeeds_stats:
  subdir: "commercial"
  versions:
    ">= 5.5.0 < 7.0.0": "/_xpack/ml/datafeeds/_stats?pretty"
    ">= 7.0.0": "/_ml/datafeeds/_stats?pretty"
```
