### ISSUE TITLE
Correct case in parameter names in the examples for import-monitoring.sh

### ISSUE THREAD

**Issue by eddieturizo** [elastic/support-diagnostics#440]
[Examples](https://github.com/elastic/support-diagnostics#monitoring-import-examples) use camel case for the cluster and index names, but the [code](https://github.com/elastic/support-diagnostics/blob/19ef80910e1f641cdbb80bb704b63258b9e2a5bb/src/main/java/com/elastic/support/monitoring/MonitoringImportInputs.java#L21-L22) suggests camel case should not be used.

**Comment by nemonster** [comment]
Fixed in 8.1.2.
