### ISSUE TITLE
Add additional GET Commands

### ISSUE THREAD

**Issue by Gunnerva** [elastic/support-diagnostics#444]
In the next version please add the below "GET" outputs:

GET _cat/templates?v -- _this is needed because it will list the contents of GET _template and GET _index_template, however GET _template does not include the data from GET _index_template
GET _index_template
GET _component_template

**Comment by CBlaisure** [comment]
What versions do these commands apply to?

**Comment by Gunnerva** [comment]
These were introduced in 7.8 of Elasticsearch.

> composable index templates introduced in Elasticsearch 7.8.
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/index-templates.html

Related docs:
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/indices-get-template.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/getting-component-templates.html

**Comment by ppf2** [comment]
These are important as we start to support customers using data streams.

**Comment by VimCommando** [comment]
@CBlaisure I reviewed the [`elastic-rest.yml`](https://github.com/VimCommando/support-diagnostics/blob/7011757cb0951a515fee83e20e5c4740296938c1/src/main/resources/elastic-rest.yml) and it looks like all the  endpoints requested here have already been added, I think we can close this issue.

**Comment by CBlaisure** [comment]
Thanks @VimCommando. Closing issue.
