### ISSUE TITLE
Add auto-scaling APIs

### ISSUE THREAD

**Issue by jakommo** [elastic/support-diagnostics#472]
[1,3,2,1]
It wold be good to GET the new autoscaling APIs into the diag, so we can review on the systems that have support for it (ESS, ECE, ECK). 

For now, it looks like that's:
[GET /_autoscaling/capacity/](https://www.elastic.co/guide/en/elasticsearch/reference/current/autoscaling-get-autoscaling-capacity.html)
[GET /_autoscaling/policy/<name>](https://www.elastic.co/guide/en/elasticsearch/reference/current/autoscaling-get-autoscaling-policy.html)

**Comment by nellicus** [comment]
this should be a quick couple of lines change. @pickypg to put up a PR

**Comment by jakommo** [comment]
Thanks friends. Do note that this is only available on ECE, ESS and ECK for now. Which is why I didn't PR it (not sure how to only hit those, if possible at all)

**Comment by pickypg** [comment]
`GET /_autoscaling/policy/` does not work without specifying an explicit name (`*` does not list), so we will have to skip this one for now.

> not sure how to only hit those, if possible at all

It's not currently. But returning a 404 isn't the end of the world.

**Comment by jakommo** [comment]
Thanks @pickypg . The policies are also in the cluster state, which should be enough for now
