### ISSUE TITLE
the dist package is missing files and directories.

### ISSUE THREAD

**Issue by luckeyca** [elastic/support-diagnostics#478]
downloaded the support-diagnostics-8.1.4-dist.zip and run ./diagnostics.sh. got error below:
Error: Could not find or load main class com.elastic.support.diagnostics.DiagnosticApp.

open up the shell script and could see this line:
"$JAVA" $DIAG_JAVA_OPTS ${DIAG_DEBUG_OPTS} -cp ${scriptDir}/config:${scriptDir}/lib/* com.elastic.support.diagnostics.DiagnosticApp "$@"

however, neither "config" nor "lib" could be found anywhere in the pacakge.

**Comment by pickypg** [comment]
Hi @luckeyca,

I just checked the distribution's `.zip` file in the release link:

https://github.com/elastic/support-diagnostics/releases/download/v8.1.4/support-diagnostics-8.1.4-dist.zip

When I unzipped it, there is a `config` and `lib` directory in there. Can you double check that you did not download the `Source code` by accident (common mistake)?

**Comment by luckeyca** [comment]
Hi @pickypg, thanks. I pretty sure I downloaded the dist file, but download again today and did see the directories now. wonder if the company firewall did something to the artifacts.

**Comment by pickypg** [comment]
No harm, no foul! Have a good weekend.

**Comment by luckeyca** [comment]
same to you. @pickypg
