### ISSUE TITLE
Kibana diagnostic APIs

### ISSUE THREAD

**Issue by CamiloSierraH** [elastic/support-diagnostics#484]
Hi everyone, 

@111andre111 has collected a great list with the APIs accesible in Kibana! I have created this new case so we check and prioritize the API we will add.

I see two aspects that we need to review for each API, so we can produce some prioritization:
- how this API will help us to troubleshooting or better understand an Issue.
- Is any information that we don't want to collect on the API response.

### Kibana APIs
Alerts/Actions
- [ ]  https://localhost:5601/api/actions/list_action_types
      - This API only bring the list of actions types, but no details about if they are used or not, so I will think this is a  `low priority` instead we can use the api/actions (already added into the diagnsotic) 
- [ ]  https://localhost:5601/api/alerts/_aggregate?default_search_operator=AND
      - We already have this data in the alerts/_find API (not sure we need this one or at least this will be in `low priority`)
- [x]  https://localhost:5601/api/alerts/_health
- [ ]  https://localhost:5601/api/alerts/list_alert_types
- [ ]  https://localhost:5601/api/triggers_actions_ui/_health

Saved Objects/Spaces
- [ ]  https://localhost:5601/api/kibana/management/saved_objects/_allowed_types
- [ ]  https://localhost:5601/api/spaces/space?include_authorized_purposes=true

Detection  ( @kostasb  or @cybersecdiva  )
- [ ]  https://localhost:5601/api/detection_engine/privileges
- [ ]  https://localhost:5601/api/lists/privileges
- [ ]  https://localhost:5601/api/security/role
- [ ]  https://localhost:5601/internal/security/_check_role_mapping_features
- [ ]  https://localhost:5601/internal/security/api_key/privileges
- [ ]  https://localhost:5601/internal/security/me

Endpoint/Fleet (this looks really interesting I need to test fleet and the API)
- [ ]  https://localhost:5601/api/endpoint/metadata
- [ ]  https://localhost:5601/api/endpoint/trusted_apps?page=1&per_page=1
- [ ]  https://localhost:5601/api/fleet/check-permissions
- [ ]  https://localhost:5601/api/fleet/package_policies?perPage=50&page=1&kuery=ingest-package-policies.package.name%3A%20endpoint
- [ ]  https://localhost:5601/api/infra/log_source_configurations/default/status

Tags ( @kostasb  or @cybersecdiva  )
- [ ]  https://localhost:5601/api/cases/tags
- [ ]  https://localhost:5601/api/detection_engine/tags
- [ ]  https://localhost:5601/api/saved_objects_tagging/tags

detections/cases  ( @kostasb  or @cybersecdiva  )
- [ ]  https://localhost:5601/api/cases/reporters
- [ ]  https://localhost:5601/api/detection_engine/index
- [ ]  https://localhost:5601/api/detection_engine/rules/_find_statuses
- [ ]  https://localhost:5601/api/detection_engine/rules/prepackaged
- [ ]  https://localhost:5601/api/detection_engine/rules/prepackaged/_status
- [ ]  https://localhost:5601/api/reporting/jobs/list?page=0

ML capabilities
- [ ]  https://localhost:5601/api/ml/data_frame/analytics
- [ ]  https://localhost:5601/api/ml/data_frame/analytics/_stats
- [ ]  https://localhost:5601/api/ml/jobs/jobs_summary
- [ ]  https://localhost:5601/api/ml/ml_capabilities
- [ ]  https://localhost:5601/api/ml/modules/get_module/
- [ ]  https://localhost:5601/api/ml/saved_objects/jobs_spaces
- [ ]  https://localhost:5601/api/ml/saved_objects/sync?simulate=true

Watcher

- [ ]  https://localhost:5601/api/watcher/watches
- The watcher data is already accessible in Elasticsearch diagnostic, the data is more accurate there as the watcher is executed in Elasticsearch. (so not sure we need this one or at least this will be in `low priority`)
- WARNING: this API can expose the Headers or login/password in Webhooks actions, if we collect this one we will need to clean that data before save it.

**Comment by 111andre111** [comment]
@CamiloSierraH Just for information, the list I provided is more or less a small extract. I have quite a very huge list of API calls because I was curious. It has more than 400 API calls and let me add it here, plus a swagger file that I've created.

[kibana-api.xlsx](https://github.com/elastic/support-diagnostics/files/6373277/kibana-api.xlsx)


[examples.spec-sorted.json.txt](https://github.com/elastic/support-diagnostics/files/6373282/examples.spec-sorted.json.txt)

**Comment by CBlaisure** [comment]
We should be very careful what API's we call and should consider load on the cluster as well as security concerns in evaluating what API's to use.  In general, we should pull only what is relevant for our troubleshooting.  

We should be mapping API calls to Support Use cases to justify the addition to the diagnostic.

**Comment by 111andre111** [comment]
@CBlaisure Absolutely agreed only due to the fact that I have a list of API calls that doesn't mean that all of them are helpful/ feasible so it absolutely makes sense to have a deeper check first.

**Comment by romain-chanu** [comment]
@CamiloSierraH - for the Kibana APIs, can we add `/api/status` as well? The utility (version 8.1.4) only gets the `/api/stats`. The `/api/status` collects status information from all the Kibana plugins - that could be handy as well for troubleshooting.

**Comment by stefnestor** [comment]
🙏🏼 request to append `GET api/task_manager/_health` which is the first thing Kibana Alerts requests for Alert investigations (e.g. https://github.com/elastic/sdh-kibana/issues/1966#issuecomment-910434713).

**Comment by CamiloSierraH** [comment]
Hey @stefnestor , the API is already on the support diagnostic if the kibana version already has that API.
```
kibana_task_manager_help:
  versions:
    ">= 7.11.0": "/api/task_manager/_health"
```
more details here: https://github.com/elastic/support-diagnostics/blob/main/src/main/resources/kibana-rest.yml

And you are right that is one of the first APIs we use to debug the alerting, for that reason since the first version we analyze the results of that API on the diagnostic analyzer https://github.com/elastic/support-kibana-analyzer (see the images for `Kibana task manager`)
If you have a specific Kibana that does not provide these results, please check the version of kibana, if >= 7.11.0 and you can reproduce the issue do not hesitate to open a new issue.
(if you can not reproduce the issue please attach the diagnostic results to the issue, if the file is not there maybe there was a timeout)

Thanks

**Comment by stefnestor** [comment]
(Noting, we originally split this out from https://github.com/elastic/support-diagnostics/issues/479#issuecomment-825148583 but it looks like the conversations continuing over there.)

**Comment by lucabelluccini** [comment]
Fleet APIs already covered:
- [x] /api/fleet/package_policies
- [x] /api/fleet/agent_policies
- [x] /api/fleet/agents
PR to add few more:
https://github.com/elastic/support-diagnostics/pull/607

**Comment by 111andre111** [comment]
Let's close this as the requestor is long time not with elastic any more and the request is as well too broad.
