### ISSUE TITLE
Change to Gradle Build

### ISSUE THREAD

**Issue by pickypg** [elastic/support-diagnostics#490]
The current Maven-based build is cumbersome and it's time to simplify it.

**Comment by SivaTharun** [comment]
@pickypg can i work on this issue, i see that the current maven build is happening via maven plugins, what is the expectation for migration to gradle, should we relay up on gradle plugins (or) move to gradle wrapper?

**Comment by SivaTharun** [comment]
Thanks @pickypg for replying, i will work to raise a draft PR, on the gradle plugin changes with in the next two to three days.

**Comment by SivaTharun** [comment]
@pickypg i have raised this draft [PR](https://github.com/elastic/support-diagnostics/pull/496), for this issue. could you review it.
