### ISSUE TITLE
Collecting snapshot count via `GET _snapshot/*/*?verbose=false`

### ISSUE THREAD

**Issue by Leaf-Lin** [elastic/support-diagnostics#521]
[1,1,2,1]

Starting from 7.15, elasticsearch will collect the total count of snapshots in a repo which can be useful for diagnotics. 
Can we please add this API call to the support diagnostics?
- https://github.com/elastic/elasticsearch/pull/76150

```
GET _snapshot/*/*?verbose=false
```

**Comment by jpcarey** [comment]
@pickypg can we pull this into the current release cycle?
