### ISSUE TITLE
Include _ingest/geoip/stats

### ISSUE THREAD

**Issue by jakelandis** [elastic/support-diagnostics#549]
Can the diagnostic also include the output of `_ingest/geoip/stats` for Elasticsearch.

https://www.elastic.co/guide/en/elasticsearch/reference/7.16/geoip-stats-api.html , this should be available as of 7.15.

**Comment by octavioranieri** [comment]
Endpoint `/_ingest/geoip/stats` has been included in 7.13.0 under https://github.com/elastic/elasticsearch/pull/70282

Submitting the PR shortly today.
