### ISSUE TITLE
running diagnostics.sh from source code does not send clear message

### ISSUE THREAD

**Issue by jguay** [elastic/support-diagnostics#562]
I think code https://github.com/elastic/support-diagnostics/pull/374 never worked for bash version

1- Download latest release source file (I know this is added by GH when creating a release and we can't disable this)
2- unzip/untar and run `scripts/diagnostics.sh` : 
```
$ scripts/diagnostics.sh
Using /usr/local/opt/openjdk@8/bin/java as Java Runtime
Using -Xms256m -Xmx2000m  for options.
Error: Could not find or load main class co.elastic.support.diagnostics.DiagnosticApp
```

While I'm there, there is another issue in the code [here](https://github.com/elastic/support-diagnostics/blob/v8.2.6/scripts/diagnostics.sh#L7) : 
```
if [  -d "libDir" ]; then
```

This is always false (there is never a directory with explicit value `libDir`, it should read
```
if [ ! -d "$libDir" ]; then
```

After this I get the expected behaviour: 
```
$ ./diagnostics.sh
Runtimes library does not exist - make sure you are running the
archive with 'dist-' in the name, not the one labeled: 'source'.
```

Also unrelated to be clear in bash the way to use a variable is `"$variable"` - the double-quote are also mandatory otherwise if the value contain a space it's not likely to work for some commands (it will replace value with `/some/folder with space` where the value should be `/some/folder\ with\ space` or `"some/folder with space"`... This does not seem to cause any issue in this case for -d check though it's not very clean code
I'll send a PR for this

**Comment by pickypg** [comment]
Closed by #563.
