### ISSUE TITLE
Some diagnostics files are not pretty printed

### ISSUE THREAD

**Issue by dakrone** [elastic/support-diagnostics#569]
In a diagnostics tarball for ES, I would say about 90% of the `.json` files are pretty printed. Would it be possible to get the others pretty printed also? This saves time since we don't have to pretty print it ourselves, and can immediate use tools like `grep` since it's not all one gigantic line.

**Comment by jpcarey** [comment]
This really goes into a balance between size and readability, and this issue had requested the removal for some of the larger ones: https://github.com/elastic/support-diagnostics/issues/467. 

Would `jq '.' filename |grep ...` be acceptable? A secondary idea might be to include in the extracted bundle a short script that would prettify all the JSON files.
