### ISSUE TITLE
[Enhancement] Fetch cluster logs in json format

### ISSUE THREAD

**Issue by psanz-estc** [elastic/support-diagnostics#626]
Looking at the current code, we are only collecting `.log` files:

```
  logs:
    elastic: "ls -alt {{LOGPATH}} | grep '{{CLUSTERNAME}}.log' | awk '{print $9}'"
```

For customers with only json output enabled, the logs collection fails...

Would it be possible to try to fetch  json files?

Thanks

**Comment by RogierSchuring** [comment]
Would be even better if the log filename and type could be derived from the log4j.properties file. Just a thought ;)

**Comment by razorworks** [comment]
> Looking at the current code, we are only collecting `.log` files:
> 
> ```
>   logs:
>     elastic: "ls -alt {{LOGPATH}} | grep '{{CLUSTERNAME}}.log' | awk '{print $9}'"
> ```
> 
> For customers with only json output enabled, the logs collection fails...
> 
> Would it be possible to try to fetch  json files?
> 
> Thanks

We are facing the same issue.
