### ISSUE TITLE
Any reason for export-monitoring.sh to limit interval between 1 to 12 hours?

### ISSUE THREAD

**Issue by Camilleli** [elastic/support-diagnostics#683]
Is there any reason that explains why export-monitoring.sh would limit the interval  from 1 to 12 hours?

https://github.com/elastic/support-diagnostics/blob/5b8cf1769d8cf1f6690667d8e606c61f90f54e4c/src/main/java/co/elastic/support/monitoring/MonitoringExportInputs.java#L146-L151

**Comment by pickypg** [comment]
I don't know the original intent, but I would assume that it related to the size of the resulting output and trying to limit that. Barring a strong reason for a longer time interval, I'm inclined to leave it in order to avoid massive uploads.
