### ISSUE TITLE
Redact passwords in .yml files

### ISSUE THREAD

**Issue by jjfalling** [elastic/support-diagnostics#73]
We need to redact passwords some of the various password that appear in the yml files.

**Comment by nemonster** [comment]
Do we have a list?  As you are aware, the passwords aren't necessarily in the open - they can be part of the URL.  Are you OK with requiring users who want this functionality to pass in some sort of formatted input file specifying what they want scrubbed?

**Comment by jjfalling** [comment]
#39 can possibly get merged into this issue.

I really think we should redact the credentials for the user instead of making them pass in a sanitized file. But maybe we should have a flag that disables this feature if needed.

I can work with dev to come up with a list of credentials that are known to exist in the various config files. The ones in a URL should be easy to spot with a regex (I think).

**Comment by nemonster** [comment]
Done, in 2.0.6

**Comment by damianpfister** [comment]
Discovered that `cloud.azure.storage.my_account.account` and `cloud.azure.storage.my_account.key` is not redacted in the `elasticsearch.yml` collection, so worth adding to the list of already redacted credentials here.

This is only used if the user has the Azure plugin installed on their cluster.

**Comment by damianpfister** [comment]
Not sure if any of these should also be redacted?

`xpack.notification.slack.account.heartbeats.url`
`xpack.notification.slack.account.healthmonitors.url`
`xpack.notification.slack.account.security.url`
